// <auto-generated />
using BackendChallenge.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendChallenge.API.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    partial class CurrencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("BackendChallenge.API.Models.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            CurrencyId = 1,
                            Code = "EUR",
                            Name = "European euro"
                        },
                        new
                        {
                            CurrencyId = 2,
                            Code = "USD",
                            Name = "United States dollar"
                        },
                        new
                        {
                            CurrencyId = 3,
                            Code = "CAD",
                            Name = "Canadian dollar"
                        },
                        new
                        {
                            CurrencyId = 4,
                            Code = "JPY",
                            Name = "Japanese yen"
                        },
                        new
                        {
                            CurrencyId = 5,
                            Code = "AUD",
                            Name = "Australian dollar"
                        },
                        new
                        {
                            CurrencyId = 6,
                            Code = "PEN",
                            Name = "Peruvian sol"
                        });
                });

            modelBuilder.Entity("BackendChallenge.API.Models.CurrencyExchange", b =>
                {
                    b.Property<int>("CurrencyExchangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyId_From")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyId_To")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Equivalent")
                        .HasColumnType("REAL");

                    b.HasKey("CurrencyExchangeId");

                    b.ToTable("CurrencyExchange");

                    b.HasData(
                        new
                        {
                            CurrencyExchangeId = 1,
                            CurrencyId_From = 1,
                            CurrencyId_To = 2,
                            Equivalent = 1.1299999999999999
                        },
                        new
                        {
                            CurrencyExchangeId = 2,
                            CurrencyId_From = 1,
                            CurrencyId_To = 3,
                            Equivalent = 1.53
                        },
                        new
                        {
                            CurrencyExchangeId = 3,
                            CurrencyId_From = 1,
                            CurrencyId_To = 4,
                            Equivalent = 120.89
                        },
                        new
                        {
                            CurrencyExchangeId = 4,
                            CurrencyId_From = 1,
                            CurrencyId_To = 5,
                            Equivalent = 1.6299999999999999
                        },
                        new
                        {
                            CurrencyExchangeId = 5,
                            CurrencyId_From = 1,
                            CurrencyId_To = 6,
                            Equivalent = 3.9700000000000002
                        },
                        new
                        {
                            CurrencyExchangeId = 6,
                            CurrencyId_From = 2,
                            CurrencyId_To = 1,
                            Equivalent = 0.89000000000000001
                        },
                        new
                        {
                            CurrencyExchangeId = 7,
                            CurrencyId_From = 2,
                            CurrencyId_To = 3,
                            Equivalent = 1.3600000000000001
                        },
                        new
                        {
                            CurrencyExchangeId = 8,
                            CurrencyId_From = 2,
                            CurrencyId_To = 4,
                            Equivalent = 107.43000000000001
                        },
                        new
                        {
                            CurrencyExchangeId = 9,
                            CurrencyId_From = 2,
                            CurrencyId_To = 5,
                            Equivalent = 1.4399999999999999
                        },
                        new
                        {
                            CurrencyExchangeId = 10,
                            CurrencyId_From = 2,
                            CurrencyId_To = 6,
                            Equivalent = 3.5299999999999998
                        },
                        new
                        {
                            CurrencyExchangeId = 11,
                            CurrencyId_From = 3,
                            CurrencyId_To = 1,
                            Equivalent = 0.65000000000000002
                        },
                        new
                        {
                            CurrencyExchangeId = 12,
                            CurrencyId_From = 3,
                            CurrencyId_To = 2,
                            Equivalent = 0.73999999999999999
                        },
                        new
                        {
                            CurrencyExchangeId = 13,
                            CurrencyId_From = 3,
                            CurrencyId_To = 4,
                            Equivalent = 79.060000000000002
                        },
                        new
                        {
                            CurrencyExchangeId = 14,
                            CurrencyId_From = 3,
                            CurrencyId_To = 5,
                            Equivalent = 1.0600000000000001
                        },
                        new
                        {
                            CurrencyExchangeId = 15,
                            CurrencyId_From = 3,
                            CurrencyId_To = 6,
                            Equivalent = 2.6000000000000001
                        },
                        new
                        {
                            CurrencyExchangeId = 16,
                            CurrencyId_From = 4,
                            CurrencyId_To = 1,
                            Equivalent = 0.0083000000000000001
                        },
                        new
                        {
                            CurrencyExchangeId = 17,
                            CurrencyId_From = 4,
                            CurrencyId_To = 2,
                            Equivalent = 0.0092999999999999992
                        },
                        new
                        {
                            CurrencyExchangeId = 18,
                            CurrencyId_From = 4,
                            CurrencyId_To = 3,
                            Equivalent = 0.012999999999999999
                        },
                        new
                        {
                            CurrencyExchangeId = 19,
                            CurrencyId_From = 4,
                            CurrencyId_To = 5,
                            Equivalent = 0.012999999999999999
                        },
                        new
                        {
                            CurrencyExchangeId = 20,
                            CurrencyId_From = 4,
                            CurrencyId_To = 6,
                            Equivalent = 0.033000000000000002
                        },
                        new
                        {
                            CurrencyExchangeId = 21,
                            CurrencyId_From = 5,
                            CurrencyId_To = 1,
                            Equivalent = 0.60999999999999999
                        },
                        new
                        {
                            CurrencyExchangeId = 22,
                            CurrencyId_From = 5,
                            CurrencyId_To = 2,
                            Equivalent = 0.68999999999999995
                        },
                        new
                        {
                            CurrencyExchangeId = 23,
                            CurrencyId_From = 5,
                            CurrencyId_To = 3,
                            Equivalent = 0.93999999999999995
                        },
                        new
                        {
                            CurrencyExchangeId = 24,
                            CurrencyId_From = 5,
                            CurrencyId_To = 4,
                            Equivalent = 74.310000000000002
                        },
                        new
                        {
                            CurrencyExchangeId = 25,
                            CurrencyId_From = 5,
                            CurrencyId_To = 6,
                            Equivalent = 2.4399999999999999
                        },
                        new
                        {
                            CurrencyExchangeId = 26,
                            CurrencyId_From = 6,
                            CurrencyId_To = 1,
                            Equivalent = 0.25
                        },
                        new
                        {
                            CurrencyExchangeId = 27,
                            CurrencyId_From = 6,
                            CurrencyId_To = 2,
                            Equivalent = 0.28000000000000003
                        },
                        new
                        {
                            CurrencyExchangeId = 28,
                            CurrencyId_From = 6,
                            CurrencyId_To = 3,
                            Equivalent = 0.29999999999999999
                        },
                        new
                        {
                            CurrencyExchangeId = 29,
                            CurrencyId_From = 6,
                            CurrencyId_To = 4,
                            Equivalent = 30.440000000000001
                        },
                        new
                        {
                            CurrencyExchangeId = 30,
                            CurrencyId_From = 6,
                            CurrencyId_To = 5,
                            Equivalent = 0.40999999999999998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
